#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH --nodes=4
#SBATCH -C gpu
#SBATCH --gpus-per-node=4
#SBATCH --gpu-bind=none
#SBATCH -q debug
#SBATCH -J debug-requeue
#SBATCH --mail-user=kgreif@uci.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3246
#SBATCH -t 0-00:30:00
#SBATCH --signal=USR1@120
#SBATCH --requeue
#SBATCH --open-mode=append

# Make job array
#SBATCH --array=2-2

# Redirect stdout and stderr to output directory separated by job number
#SBATCH -o ./outfiles/%x-%A-%a.out
#SBATCH -e ./outfiles/%x-%A-%a.err

# Set up environment
module load conda
conda activate ajets

# Set up wandb
export WANDB__SERVICE_WAIT=400
wandb login

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# run the application:
python run_omnifold.py --config_path ./cli/base_ensemble.yml --ensemble_index $SLURM_ARRAY_TASK_ID
sleep 120 # sleep for 2 minutes to allow slurm to send SIGTERM in case of preemption