#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH --nodes=4
#SBATCH -C gpu
#SBATCH --gres=gpu:4
#SBATCH --ntasks-per-node=4
#SBATCH -q debug
#SBATCH -J pretrain
#SBATCH --mail-user=kgreif@uci.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3246
#SBATCH -t 0-00:20:00

# Make job array
#SBATCH --array=1-1

# Redirect stdout and stderr to output directory separated by job number
#SBATCH -o ./outfiles/%x-%A-%a.out
#SBATCH -e ./outfiles/%x-%A-%a.err

# Set up environment
module load conda
conda activate ajets

# Set up wandb
export WANDB__SERVICE_WAIT=300
wandb login

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# run the application:
# Since the parent process just handles calling the subprocesses for training / eval, run it one 1 core and 1 node
python run_omnifold.py --config_path ./cli/multi_node.yml --ensemble_index $SLURM_ARRAY_TASK_ID