#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH --nodes=4
#SBATCH -C gpu
#SBATCH --ntasks-per-node=4
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=none
#SBATCH -q regular
#SBATCH -J pretrain_ens01
#SBATCH --mail-user=kgreif@uci.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3246
#SBATCH -t 0-12:00:00

# Make job array
#SBATCH --array=1-10

# Redirect stdout and stderr to output directory separated by job number
#SBATCH -o ./outfiles/%x-%A-%a.out
#SBATCH -e ./outfiles/%x-%A-%a.err

# Function to handle SIGUSR1
cleanup() {
    echo "Caught SIGUSR1 in Bash script. Propagating signal..."
    kill -SIGUSR1 $(jobs -p) # Sends SIGUSR1 to all child processes
}

# Set up environment
module load conda
conda activate ajets

# Set up wandb
export WANDB__SERVICE_WAIT=300
wandb login

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

# Trap SIGUSR1 and call timeout operations
trap cleanup SIGUSR1

# run the application:
# Since the parent process just handles calling the subprocesses for training / eval, run it one 1 core and 1 node
python run_omnifold.py --config_path ./cli/single_node.yml &

# Wait for all child processes to complete
wait