#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH --ntasks-per-node=4
#SBATCH -C gpu
#SBATCH -G 4
#SBATCH -q regular
#SBATCH -J track_wass_1
#SBATCH --mail-user=kgreif@uci.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3246
#SBATCH -t 6:0:0

# Set up environment
module load conda
conda activate zjets

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application: 
# applications may perform better with --gpu-bind=none instead of --gpu-bind=single:1
srun -n 4 -c 32 --cpu_bind=cores -G 4 --gpu-bind=none python lightning_train.py --seed $((RANDOM))