#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH --nodes=4
#SBATCH -C gpu
#SBATCH --gpus-per-node=4
#SBATCH --gpu-bind=none
#SBATCH -q regular
#SBATCH -J v4-pretrain-step2
#SBATCH --mail-user=kgreif@uci.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3246
#SBATCH -t 0-04:00:00
#SBATCH --array=1-10

# Redirect stdout and stderr to output directory separated by job number
#SBATCH -o ./outfiles/%x-%A-%a.out
#SBATCH -e ./outfiles/%x-%A-%a.err

# Set up environment
module load conda
conda activate zfjets

# Set up wandb
export WANDB__SERVICE_WAIT=400
wandb login

# run the application:
srun --nodes 4 --ntasks-per-node 4 --gpus-per-task 1 --gpu-bind=none --cpus-per-task 32 --cpu-bind=none python run_pretrain.py --config ./cli/zjets-v4-pretrain.yml --split_seed 484 --index $SLURM_ARRAY_TASK_ID --step 2